import {
  BedDouble,
  Briefcase,
  ClipboardList,
  Code2,
  Cpu,
  EyeOff,
  Globe2,
  GraduationCap,
  HeartPulse,
  HelpCircle,
  Laptop,
  Layers,
  Network,
  Printer,
  Puzzle,
  RefreshCcw,
  Ruler,
  Search,
  Server,
  ShoppingBag,
  Sprout,
  Tablet,
  TrendingUp,
  Truck,
  Unplug,
  Workflow,
  type LucideIcon,
} from "lucide-react";

const icons: Record<string, LucideIcon> = {
  "bed-double": BedDouble,
  briefcase: Briefcase,
  clipboard: ClipboardList,
  code: Code2,
  cpu: Cpu,
  "eye-off": EyeOff,
  globe: Globe2,
  "graduation-cap": GraduationCap,
  hardware: Server,
  "heart-pulse": HeartPulse,
  help: HelpCircle,
  laptop: Laptop,
  layers: Layers,
  network: Network,
  printer: Printer,
  puzzle: Puzzle,
  ruler: Ruler,
  search: Search,
  server: Server,
  "shopping-bag": ShoppingBag,
  sprout: Sprout,
  tablet: Tablet,
  transform: RefreshCcw,
  "trending-up": TrendingUp,
  truck: Truck,
  unplug: Unplug,
  workflow: Workflow,
};

/** Renders a decorative lucide icon by the name used in content/copy files. */
export function Icon({ name, className }: { name: string; className?: string }) {
  const Component = icons[name] ?? Puzzle;
  return <Component aria-hidden="true" className={className} />;
}
